/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.Dufins.Developer.HRManagement.Forms;

import Util.Util;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.TableColumn;

/**
 *
 * @author Owner
 */
public class Holiday extends javax.swing.JPanel {

    /**
     * Creates new form Holiday
     */
    Connection connection = null;
    PreparedStatement pstmt = null;
    int flag = 0;
    int weekflag = 0;

    public Holiday() {
        initComponents();
        start_date.setDate(new Date());
        rbSingleday.setSelected(true);
        txtDesc.setText("");
        ChkSun.setSelected(true);
        end_date.setEnabled(false);
        end_date.setDate(start_date.getDate());
        showHoliday();
        showWeek();
    }

    private void showHoliday() {
        try {
            connection = Util.getConnection();
            String sql = "select start_date, end_date, description from holiday_setting where year(start_date) = '" + start_date.getDate().toString().substring(24) + "' ";
            pstmt = connection.prepareStatement(sql);
            ResultSet rs1 = pstmt.executeQuery();
            jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Holiday Start Date");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Holiday End Date");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Description");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showWeek() {
        try {
            pstmt = connection.prepareStatement("Select * from weekly_holiday_setting where id = 1");
            ResultSet rs = pstmt.executeQuery();
            rs.next();
            if (rs.getString(2).equals("Y")) {
                ChkSun.setSelected(true);
            } else {
                ChkSun.setSelected(false);
            }
            if (rs.getString(3).equals("Y")) {
                ChkMon.setSelected(true);
            } else {
                ChkMon.setSelected(false);
            }
            if (rs.getString(4).equals("Y")) {
                ChkTue.setSelected(true);
            } else {
                ChkTue.setSelected(false);
            }
            if (rs.getString(5).equals("Y")) {
                ChkWed.setSelected(true);
            } else {
                ChkWed.setSelected(false);
            }
            if (rs.getString(6).equals("Y")) {
                ChkThu.setSelected(true);
            } else {
                ChkThu.setSelected(false);
            }
            if (rs.getString(7).equals("Y")) {
                ChkFri.setSelected(true);
            } else {
                ChkFri.setSelected(false);
            }
            if (rs.getString(8).equals("Y")) {
                ChkSat.setSelected(true);
            } else {
                ChkSat.setSelected(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbSingleday = new javax.swing.JRadioButton();
        rbMultipleDay = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        start_date = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        end_date = new com.toedter.calendar.JDateChooser();
        BtnAdd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ChkSun = new javax.swing.JCheckBox();
        ChkMon = new javax.swing.JCheckBox();
        ChkTue = new javax.swing.JCheckBox();
        ChkWed = new javax.swing.JCheckBox();
        ChkThu = new javax.swing.JCheckBox();
        ChkFri = new javax.swing.JCheckBox();
        ChkSat = new javax.swing.JCheckBox();
        BtnApply = new javax.swing.JLabel();
        BtnCancel = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Company Holidays Settings", 2, 3, new java.awt.Font("Arial", 1, 18), java.awt.Color.black)); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settings", 0, 3, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 51))); // NOI18N

        rbSingleday.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbSingleday);
        rbSingleday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbSingleday.setText("Single Day");
        rbSingleday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSingledayActionPerformed(evt);
            }
        });

        rbMultipleDay.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbMultipleDay);
        rbMultipleDay.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbMultipleDay.setText("Multiple Days");
        rbMultipleDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMultipleDayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Date :");

        start_date.setBackground(new java.awt.Color(255, 255, 255));
        start_date.setDate(new Date());
        start_date.setDateFormatString("dd-MM-yyyy");
        start_date.setOpaque(false);
        start_date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                start_datePropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("End Date :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Description :");

        end_date.setDate(new Date());
        end_date.setDateFormatString("dd-MM-yyyy");
        end_date.setOpaque(false);
        end_date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                end_datePropertyChange(evt);
            }
        });

        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        BtnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        BtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nilaicon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnAdd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbSingleday)
                                .addGap(28, 28, 28)
                                .addComponent(rbMultipleDay))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(end_date, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSingleday)
                            .addComponent(rbMultipleDay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(start_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(end_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        Color ppColor = new Color(0, 51, 255, 70);
        jTable1.setShowVerticalLines(true);
        jTable1.setBackground(Color.WHITE);
        //jTable1.setShowHorizontalLines(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Weekly Holidays", 0, 3, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 51))); // NOI18N

        ChkSun.setBackground(new java.awt.Color(255, 255, 255));
        ChkSun.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ChkSun.setText("Sunday");

        ChkMon.setBackground(new java.awt.Color(255, 255, 255));
        ChkMon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ChkMon.setText("Monday");

        ChkTue.setBackground(new java.awt.Color(255, 255, 255));
        ChkTue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ChkTue.setText("Tuesday");

        ChkWed.setBackground(new java.awt.Color(255, 255, 255));
        ChkWed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ChkWed.setText("Wednesday");

        ChkThu.setBackground(new java.awt.Color(255, 255, 255));
        ChkThu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ChkThu.setText("Thursday");

        ChkFri.setBackground(new java.awt.Color(255, 255, 255));
        ChkFri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ChkFri.setText("Friday");

        ChkSat.setBackground(new java.awt.Color(255, 255, 255));
        ChkSat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ChkSat.setText("Saturday");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ChkSun, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChkMon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ChkWed)
                                .addGap(16, 16, 16)
                                .addComponent(ChkThu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ChkFri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChkTue, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ChkSat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkSun)
                    .addComponent(ChkMon)
                    .addComponent(ChkTue))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkWed)
                    .addComponent(ChkThu)
                    .addComponent(ChkFri))
                .addGap(18, 18, 18)
                .addComponent(ChkSat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnApply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save_as.png"))); // NOI18N
        BtnApply.setToolTipText("Apply Settings");
        BtnApply.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        BtnApply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnApply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnApplyMouseClicked(evt);
            }
        });

        BtnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Crystal_button_cancel.png"))); // NOI18N
        BtnCancel.setToolTipText("Apply Settings");
        BtnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        BtnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnApply)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCancel)
                    .addComponent(BtnApply))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int row = jTable1.getSelectedRow();
            String start = jTable1.getValueAt(row, 0).toString();
            String end = jTable1.getValueAt(row, 1).toString();
            String desc = jTable1.getValueAt(row, 2).toString();
            String sql = "select * from holiday_setting where start_date = '" + start + "' and end_date = '" + end + "' and description = '" + desc + "'";
            pstmt = connection.prepareStatement(sql);
            ResultSet rs1 = pstmt.executeQuery();
            if (rs1.next()) {
                flag = rs1.getInt(1);
                start_date.setDate(rs1.getDate(2));
                end_date.setDate(rs1.getDate(3));
                txtDesc.setText(rs1.getString(4));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    }//GEN-LAST:event_formMouseClicked

    private void BtnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtnCancelMouseClicked

    private void rbSingledayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSingledayActionPerformed
        // TODO add your handling code here:
        if (rbSingleday.isSelected()) {
            end_date.setEnabled(false);
            end_date.setDate(start_date.getDate());
        }
    }//GEN-LAST:event_rbSingledayActionPerformed

    private void rbMultipleDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMultipleDayActionPerformed
        // TODO add your handling code here:
        if (rbMultipleDay.isSelected()) {
            end_date.setEnabled(true);
            end_date.setDate(start_date.getDate());
        }
    }//GEN-LAST:event_rbMultipleDayActionPerformed

    private void start_datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_start_datePropertyChange
        // TODO add your handling code here:
        end_date.setDate(start_date.getDate());
        showHoliday();
    }//GEN-LAST:event_start_datePropertyChange

    private void end_datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_end_datePropertyChange
        // TODO add your handling code here:
        if (start_date.getDate().after(end_date.getDate())) {
            JOptionPane.showMessageDialog(this, "Please choose correct date value.");
            end_date.setDate(start_date.getDate());
        }
    }//GEN-LAST:event_end_datePropertyChange

    private void BtnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddMouseClicked
        // TODO add your handling code here:
        flag = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            pstmt = connection.prepareStatement("insert into holiday_temp_setting(start_date, end_date, description) values (?, ?, ?)");
            pstmt.setString(1, sdf.format(start_date.getDate()));
            pstmt.setString(2, sdf.format(end_date.getDate()));
            pstmt.setString(3, txtDesc.getText().trim());
            int a = pstmt.executeUpdate();
            if (a > 0) {
                String sql = "select start_date, end_date, description from holiday_temp_setting";
                pstmt = connection.prepareStatement(sql);
                ResultSet rs1 = pstmt.executeQuery();
                jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
                jTable1.getColumnModel().getColumn(0).setHeaderValue("Holiday Start Date");
                jTable1.getColumnModel().getColumn(1).setHeaderValue("Holiday End Date");
                jTable1.getColumnModel().getColumn(2).setHeaderValue("Description");
            } else {
                JOptionPane.showMessageDialog(this, "Error while updating data.");
            }
        } catch (SQLException | HeadlessException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnAddMouseClicked

    public void setWeek() {
        try {
            pstmt = connection.prepareStatement("update weekly_holiday_setting set sun_holiday = ?, mon_holiday = ?, tue_holiday = ?, wed_holiday = ?, thu_holiday = ?, fri_holiday = ?, sat_holiday = ? where id = 1");
            if (ChkSun.isSelected()) {
                pstmt.setString(1, "Y");
            } else {
                pstmt.setString(1, "N");
            }
            if (ChkMon.isSelected()) {
                pstmt.setString(2, "Y");
            } else {
                pstmt.setString(2, "N");
            }
            if (ChkTue.isSelected()) {
                pstmt.setString(3, "Y");
            } else {
                pstmt.setString(3, "N");
            }
            if (ChkWed.isSelected()) {
                pstmt.setString(4, "Y");
            } else {
                pstmt.setString(4, "N");
            }
            if (ChkThu.isSelected()) {
                pstmt.setString(5, "Y");
            } else {
                pstmt.setString(5, "N");
            }
            if (ChkFri.isSelected()) {
                pstmt.setString(6, "Y");
            } else {
                pstmt.setString(6, "N");
            }
            if (ChkSat.isSelected()) {
                pstmt.setString(7, "Y");
            } else {
                pstmt.setString(7, "N");
            }
            weekflag = pstmt.executeUpdate();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void BtnApplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnApplyMouseClicked
        // TODO add your handling code here:
        try {
            int a = 0;
            setWeek();
            if (flag == 0) {
                pstmt = connection.prepareStatement("insert into holiday_Setting (start_date, end_date, description) select start_date, end_date, description from holiday_temp_setting");
                a = pstmt.executeUpdate();
                if (a > 0) {
                    pstmt = connection.prepareStatement("truncate table holiday_temp_setting ");
                    a = pstmt.executeUpdate();
                    if (a > 0) {
                        JOptionPane.showMessageDialog(this, "Holiday data successfully updated.");
                        showHoliday();
                        showWeek();
                    }
                }
            } else {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String sql = "update holiday_setting set start_date = ?, end_date = ?, description = ? where id = " + flag + " ";
                pstmt = connection.prepareStatement(sql);
                pstmt.setString(1, sdf.format(start_date.getDate()));
                pstmt.setString(2, sdf.format(end_date.getDate()));
                pstmt.setString(3, txtDesc.getText().trim());
                a = pstmt.executeUpdate();
                if (a > 0) {
                    JOptionPane.showMessageDialog(this, "Data successfully updated");
                    showHoliday();
                    showWeek();
                }
            }

            if (weekflag > 0 && a == 0) {
                JOptionPane.showMessageDialog(this, "Week holiday successfully updated");
                showWeek();
            }
        } catch (SQLException | HeadlessException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnApplyMouseClicked

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {
            try {
                pstmt = connection.prepareStatement("delete from holiday_setting where id = " + flag + " ");
                int a = pstmt.executeUpdate();
                if (a > 0) {
                    JOptionPane.showMessageDialog(null, "Successfully deleted");
                    flag = 0;
                    start_date.setDate(new Date());
                    end_date.setDate(start_date.getDate());
                    txtDesc.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            showHoliday();
        }

    }//GEN-LAST:event_jTable1KeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAdd;
    private javax.swing.JLabel BtnApply;
    private javax.swing.JLabel BtnCancel;
    private javax.swing.JCheckBox ChkFri;
    private javax.swing.JCheckBox ChkMon;
    private javax.swing.JCheckBox ChkSat;
    private javax.swing.JCheckBox ChkSun;
    private javax.swing.JCheckBox ChkThu;
    private javax.swing.JCheckBox ChkTue;
    private javax.swing.JCheckBox ChkWed;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser end_date;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbMultipleDay;
    private javax.swing.JRadioButton rbSingleday;
    private com.toedter.calendar.JDateChooser start_date;
    private javax.swing.JTextField txtDesc;
    // End of variables declaration//GEN-END:variables
}
