/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.Dufins.Developer.HRManagement.Forms;

import Util.Util;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class SalaryParameter extends javax.swing.JPanel {

    /**
     * Creates new form SalaryParameter
     */
    Connection connection = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    public SalaryParameter() {
        initComponents();
        clear();
        try {
            connection = Util.getConnection();
            retFacilitySetting();
            retDeductionDetails();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void retFacilitySetting() {
        try {
            pstmt = connection.prepareStatement("select * from facility_setting");
            rs = pstmt.executeQuery();
            while (rs.next()) {
                if (rs.getString(1).equals("OT")) {
                    CmbOT.setSelectedItem(rs.getString(2));
                    txtOT.setText(rs.getString(3));
                }
                if (rs.getString(1).equals("PF")) {
                    if (rs.getString(3).contains("%")) {
                        rbPFRate.setSelected(true);
                        txt_RatePF.setText(rs.getString(3).substring(0, rs.getString(3).length() - 1));
                    } else {
                        txt_AmtPF.setText(rs.getString(3).trim());
                        rbPFAmt.setSelected(true);
                    }
                }
                if (rs.getString(1).equals("Mess")) {
                    txt_Mess.setText(rs.getString(3));
                }
                if (rs.getString(1).equals("ESI")) {
                    if (rs.getString(3).contains("%")) {
                        rbESIRate.setSelected(true);
                        txt_RateESI.setText(rs.getString(3).substring(0, rs.getString(3).length() - 1));
                    } else {
                        txt_AmountESI.setText(rs.getString(3));
                        rbESIAmt.setSelected(true);
                    }
                }
                if (rs.getString(1).equals("Conveyance")) {
                    txt_Con.setText(rs.getString(3));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void retDeductionDetails() {
        try {
            pstmt = connection.prepareStatement("select * from deduction_details");
            rs = pstmt.executeQuery();
            while (rs.next()) {
                if (rs.getString(1).equalsIgnoreCase("HD")) {
                    CmbHH.setSelectedItem(rs.getString(2));
                    CmbHM.setSelectedItem(rs.getString(3));
                }
                if (rs.getString(1).equalsIgnoreCase("LCEL")) {
                    CmbFH.setSelectedItem(rs.getString(2));
                    CmbFM.setSelectedItem(rs.getString(3));
                    CmbLC.setSelectedItem(rs.getString(4));
                    if (rs.getString(5).contains(":HD")) {
                        CmbNHD.setSelectedItem(rs.getString(5).substring(0, rs.getString(5).length() - 3));
                        rbNHD.setSelected(true);
                    } else {
                        CmbNFD.setSelectedItem(rs.getString(5).substring(0, rs.getString(5).length() - 3));
                        rbNFD.setSelected(true);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clear() {
        CmbOT.setEnabled(false);
        CmbFH.setEnabled(false);
        CmbFM.setEnabled(false);
        CmbHH.setEnabled(false);
        CmbHM.setEnabled(false);
        CmbLC.setEnabled(false);
        CmbNFD.setEnabled(false);
        CmbNHD.setEnabled(false);
        txtOT.setEnabled(false);
        txt_AmountESI.setEnabled(false);
        txt_AmtPF.setEnabled(false);
        txt_Con.setEnabled(false);
        txt_Mess.setEnabled(false);
        txt_RateESI.setEnabled(false);
        txt_RatePF.setEnabled(false);
        rbNFD.setEnabled(false);
        rbNHD.setEnabled(false);
        rbPFAmt.setEnabled(false);
        rbPFRate.setEnabled(false);
        rbESIAmt.setEnabled(false);
        rbESIRate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ChkOT = new javax.swing.JCheckBox();
        CmbOT = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtOT = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        CHkPF = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txt_RatePF = new javax.swing.JTextField();
        rbPFRate = new javax.swing.JRadioButton();
        rbPFAmt = new javax.swing.JRadioButton();
        txt_AmtPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbESIAmt = new javax.swing.JRadioButton();
        txt_AmountESI = new javax.swing.JTextField();
        txt_RateESI = new javax.swing.JTextField();
        rbESIRate = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        ChkESI = new javax.swing.JCheckBox();
        ChkMess = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txt_Mess = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ChkCon = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txt_Con = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ChkHD = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        CmbHH = new javax.swing.JComboBox();
        CmbHM = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        ChkLC = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        CmbFH = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        CmbFM = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CmbLC = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        rbNHD = new javax.swing.JRadioButton();
        CmbNHD = new javax.swing.JComboBox();
        rbNFD = new javax.swing.JRadioButton();
        CmbNFD = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Btn_applySetting = new javax.swing.JLabel();
        BtnClose = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salary Parameter", 2, 3, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 51))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Over Time Details", 0, 3, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Per Day OT maximum hours :");

        ChkOT.setBackground(new java.awt.Color(255, 255, 255));
        ChkOT.setText("Over Time(OT) facility");
        ChkOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkOTActionPerformed(evt);
            }
        });

        CmbOT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Wages per hour :");

        txtOT.setText(" ");
        txtOT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOTKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkOT)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CmbOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOT, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ChkOT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CmbOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deduction Detail", 0, 3, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 51))); // NOI18N

        CHkPF.setBackground(new java.awt.Color(255, 255, 255));
        CHkPF.setText("Provident Fund(P.F) facility :");
        CHkPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHkPFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("%");

        txt_RatePF.setText(" ");
        txt_RatePF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RatePFKeyTyped(evt);
            }
        });

        rbPFRate.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbPFRate);
        rbPFRate.setText("Rate :");

        rbPFAmt.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbPFAmt);
        rbPFAmt.setText("Amount :");

        txt_AmtPF.setText(" ");
        txt_AmtPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_AmtPFKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Rs.");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Rs.");

        rbESIAmt.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbESIAmt);
        rbESIAmt.setText("Amount :");

        txt_AmountESI.setText(" ");
        txt_AmountESI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_AmountESIKeyTyped(evt);
            }
        });

        txt_RateESI.setText(" ");
        txt_RateESI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RateESIKeyTyped(evt);
            }
        });

        rbESIRate.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbESIRate);
        rbESIRate.setText("Rate :");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("%");

        ChkESI.setBackground(new java.awt.Color(255, 255, 255));
        ChkESI.setText("E.S.I facility :");
        ChkESI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkESIActionPerformed(evt);
            }
        });

        ChkMess.setBackground(new java.awt.Color(255, 255, 255));
        ChkMess.setText("Mess facility :");
        ChkMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkMessActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Mess charges :");

        txt_Mess.setText(" ");
        txt_Mess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MessKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Rs.");

        ChkCon.setBackground(new java.awt.Color(255, 255, 255));
        ChkCon.setText("Conveyance facility :");
        ChkCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkConActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Conveyance charges :");

        txt_Con.setText(" ");
        txt_Con.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ConKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Rs.");

        ChkHD.setBackground(new java.awt.Color(255, 255, 255));
        ChkHD.setText("Half day duration considered as deduction :");
        ChkHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkHDActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Set Half day hour :");

        CmbHH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        CmbHM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60" }));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Set Half day min :");

        ChkLC.setBackground(new java.awt.Color(255, 255, 255));
        ChkLC.setText("LC/EL considered as deduction");
        ChkLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkLCActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Flexible hour :");

        CmbFH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Flexible min :");

        CmbFM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60" }));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Set number of LC/EL converted in Half day or Full day deduction  :");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("LC / EL :");

        CmbLC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Convert in  :");

        rbNHD.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rbNHD);
        rbNHD.setText("Number of half day  :");

        CmbNHD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        rbNFD.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rbNFD);
        rbNFD.setText("Number of full day  :");

        CmbNFD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        jLabel41.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel41.setText(" LC/EL Stands For Late Coming / Early Leaving.");

        jLabel42.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel42.setText("Note  :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChkLC)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(40, 40, 40)
                                        .addComponent(CmbFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(CmbHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(CmbFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(CmbHM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(ChkHD)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(68, 68, 68)
                                .addComponent(CmbLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbNFD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbNHD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CmbNHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CmbNFD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel41)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChkMess)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Mess, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(CHkPF)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbPFAmt)
                                    .addComponent(rbPFRate, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_RatePF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_AmtPF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ChkESI)
                                .addComponent(rbESIAmt)
                                .addComponent(rbESIRate, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChkCon)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_Con, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txt_RateESI, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txt_AmountESI, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CHkPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_RatePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rbPFRate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_AmtPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(rbPFAmt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChkMess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Mess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_RateESI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(11, 11, 11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_AmountESI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(60, 60, 60))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(ChkESI)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbESIRate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbESIAmt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ChkCon)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_Con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ChkHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(CmbHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChkLC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(CmbFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CmbHM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(CmbFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(CmbLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(rbNHD)
                    .addComponent(CmbNHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNFD)
                    .addComponent(CmbNFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nilaicon.png"))); // NOI18N

        Btn_applySetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save_as.png"))); // NOI18N
        Btn_applySetting.setToolTipText("Apply Salary Setting");
        Btn_applySetting.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        Btn_applySetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_applySetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_applySettingMouseClicked(evt);
            }
        });

        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Crystal_button_cancel.png"))); // NOI18N
        BtnClose.setToolTipText("Close Panel");
        BtnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        BtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_applySetting)
                        .addGap(18, 18, 18)
                        .addComponent(BtnClose))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_applySetting)
                    .addComponent(BtnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCloseMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtnCloseMouseClicked

    private void Btn_applySettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_applySettingMouseClicked
        // TODO add your handling code here:
        try {
            connection.setAutoCommit(false);
            pstmt = connection.prepareStatement("update facility_setting set max_time = ?, rate = ? where parameter_type = ?");
            //for overtime details
            pstmt.setString(1, CmbOT.getSelectedItem().toString());
            pstmt.setString(2, txtOT.getText().trim());
            pstmt.setString(3, "OT".trim());
            pstmt.addBatch();
            //for PF details
            pstmt.setString(1, "0");
            String pfrate = (rbPFRate.isSelected()) ? txt_RatePF.getText().trim() + "%" : txt_AmtPF.getText().trim();
            pstmt.setString(2, pfrate);
            pstmt.setString(3, "PF".trim());
            pstmt.addBatch();
            //for Mess details
            pstmt.setString(1, "0");
            pstmt.setString(2, txt_Mess.getText().trim());
            pstmt.setString(3, "Mess".trim());
            pstmt.addBatch();
            //for ESI details
            pstmt.setString(1, "0");
            String esirate = (rbESIRate.isSelected()) ? txt_RateESI.getText().trim() + "%" : txt_AmountESI.getText().trim();
            pstmt.setString(2, esirate.trim());
            pstmt.setString(3, "ESI".trim());
            pstmt.addBatch();
            //for conveyance
            pstmt.setString(1, "0");
            pstmt.setString(2, txt_Con.getText().trim());
            pstmt.setString(3, "Conveyance".trim());
            pstmt.addBatch();

            int a[] = pstmt.executeBatch();

            pstmt = connection.prepareStatement("update deduction_details set time_hrs = ?, time_min = ?, set_day = ?, max_day = ? where attribute = ?");
            //for half-day deduction
            pstmt.setString(1, CmbHH.getSelectedItem().toString());
            pstmt.setString(2, CmbHM.getSelectedItem().toString());
            pstmt.setString(3, "0");
            pstmt.setString(4, "0");
            pstmt.setString(5, "HD".trim());
            pstmt.addBatch();
            //for LC/EL
            pstmt.setString(1, CmbFH.getSelectedItem().toString());
            pstmt.setString(2, CmbFM.getSelectedItem().toString());
            pstmt.setString(3, CmbLC.getSelectedItem().toString());
            String maxday = (rbNHD.isSelected()) ? CmbNHD.getSelectedItem().toString() + ":HD" : CmbNFD.getSelectedItem().toString() + ":FD";
            pstmt.setString(4, maxday);
            pstmt.setString(5, "LCEL".trim());
            pstmt.addBatch();

            int b[] = pstmt.executeBatch();
            if (a.length > 0 && b.length > 0) {
                JOptionPane.showMessageDialog(this, "Global setting for salary parameter is successfully updated.");
                retFacilitySetting();
            } else {
                JOptionPane.showMessageDialog(this, "Error while updating salary parameter setting.");
                return;
            }
            connection.commit();
        } catch (SQLException | HeadlessException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Btn_applySettingMouseClicked

    private void ChkOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkOTActionPerformed
        // TODO add your handling code here:
        if (ChkOT.isSelected()) {
            CmbOT.setEnabled(true);
            txtOT.setEnabled(true);
        } else {
            CmbOT.setEnabled(false);
            txtOT.setEnabled(false);
        }
    }//GEN-LAST:event_ChkOTActionPerformed

    private void CHkPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHkPFActionPerformed
        // TODO add your handling code here:
        if (CHkPF.isSelected()) {
            txt_RatePF.setEnabled(true);
            txt_AmtPF.setEnabled(true);
            rbPFAmt.setEnabled(true);
            rbPFRate.setEnabled(true);
        } else {
            txt_RatePF.setEnabled(false);
            txt_AmtPF.setEnabled(false);
            rbPFAmt.setEnabled(false);
            rbPFRate.setEnabled(false);
        }
    }//GEN-LAST:event_CHkPFActionPerformed

    private void ChkESIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkESIActionPerformed
        // TODO add your handling code here:
        if (ChkESI.isSelected()) {
            txt_RateESI.setEnabled(true);
            txt_AmountESI.setEnabled(true);
            rbESIAmt.setEnabled(true);
            rbESIRate.setEnabled(true);
        } else {
            txt_RateESI.setEnabled(false);
            txt_AmountESI.setEnabled(false);
            rbESIAmt.setEnabled(false);
            rbESIRate.setEnabled(false);
        }
    }//GEN-LAST:event_ChkESIActionPerformed

    private void ChkMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkMessActionPerformed
        // TODO add your handling code here:
        if (ChkMess.isSelected()) {
            txt_Mess.setEnabled(true);
        } else {
            txt_Mess.setEnabled(false);
        }
    }//GEN-LAST:event_ChkMessActionPerformed

    private void ChkConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkConActionPerformed
        // TODO add your handling code here:
        if (ChkCon.isSelected()) {
            txt_Con.setEnabled(true);
        } else {
            txt_Con.setEnabled(false);
        }
    }//GEN-LAST:event_ChkConActionPerformed

    private void ChkHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkHDActionPerformed
        // TODO add your handling code here:
        if (ChkHD.isSelected()) {
            CmbHH.setEnabled(true);
            CmbHM.setEnabled(true);
        } else {
            CmbHH.setEnabled(false);
            CmbHM.setEnabled(false);
        }
    }//GEN-LAST:event_ChkHDActionPerformed

    private void ChkLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkLCActionPerformed
        // TODO add your handling code here:
        if (ChkLC.isSelected()) {
            CmbFH.setEnabled(true);
            CmbFM.setEnabled(true);
            CmbLC.setEnabled(true);
            CmbNFD.setEnabled(true);
            CmbNHD.setEnabled(true);
            rbNFD.setEnabled(true);
            rbNHD.setEnabled(true);
        } else {
            CmbFH.setEnabled(false);
            CmbFM.setEnabled(false);
            CmbLC.setEnabled(false);
            CmbNFD.setEnabled(false);
            CmbNHD.setEnabled(false);
            rbNFD.setEnabled(false);
            rbNHD.setEnabled(false);
        }
    }//GEN-LAST:event_ChkLCActionPerformed

    private void txtOTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOTKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch) && !(evt.getKeyChar() == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtOTKeyTyped

    private void txt_RatePFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RatePFKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch) && !(evt.getKeyChar() == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_RatePFKeyTyped

    private void txt_AmtPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AmtPFKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch) && !(evt.getKeyChar() == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_AmtPFKeyTyped

    private void txt_RateESIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RateESIKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch) && !(evt.getKeyChar() == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_RateESIKeyTyped

    private void txt_AmountESIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AmountESIKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch) && !(evt.getKeyChar() == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_AmountESIKeyTyped

    private void txt_MessKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MessKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch) && !(evt.getKeyChar() == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_MessKeyTyped

    private void txt_ConKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ConKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if (!Character.isDigit(ch) && !(evt.getKeyChar() == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ConKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnClose;
    private javax.swing.JLabel Btn_applySetting;
    private javax.swing.JCheckBox CHkPF;
    private javax.swing.JCheckBox ChkCon;
    private javax.swing.JCheckBox ChkESI;
    private javax.swing.JCheckBox ChkHD;
    private javax.swing.JCheckBox ChkLC;
    private javax.swing.JCheckBox ChkMess;
    private javax.swing.JCheckBox ChkOT;
    private javax.swing.JComboBox CmbFH;
    private javax.swing.JComboBox CmbFM;
    private javax.swing.JComboBox CmbHH;
    private javax.swing.JComboBox CmbHM;
    private javax.swing.JComboBox CmbLC;
    private javax.swing.JComboBox CmbNFD;
    private javax.swing.JComboBox CmbNHD;
    private javax.swing.JComboBox CmbOT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbESIAmt;
    private javax.swing.JRadioButton rbESIRate;
    private javax.swing.JRadioButton rbNFD;
    private javax.swing.JRadioButton rbNHD;
    private javax.swing.JRadioButton rbPFAmt;
    private javax.swing.JRadioButton rbPFRate;
    private javax.swing.JTextField txtOT;
    private javax.swing.JTextField txt_AmountESI;
    private javax.swing.JTextField txt_AmtPF;
    private javax.swing.JTextField txt_Con;
    private javax.swing.JTextField txt_Mess;
    private javax.swing.JTextField txt_RateESI;
    private javax.swing.JTextField txt_RatePF;
    // End of variables declaration//GEN-END:variables
}
