/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.Dufins.Developer.STManagement.Forms;

import Util.Coloumnautosizer;
import Util.NumToWords;
import Util.Util;
import java.awt.BasicStroke;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author NITISH SRIVASTAVA
 */
public class StudentReport extends javax.swing.JInternalFrame implements Printable {

    /**
     * Creates new form StudentReport
     */
    Connection con = null;
    Statement stmt = null;
    PreparedStatement psmnt = null;
    ResultSet rs = null;
    String selection = null;
    int rowcount;
    String r1;
    int from = 0;
    int rfrom = 0;
    int row = 0;

    public StudentReport() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_First = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        btn_Forward = new javax.swing.JButton();
        btn_Last = new javax.swing.JButton();
        btn_First1 = new javax.swing.JButton();
        btn_Back1 = new javax.swing.JButton();
        btn_Forward1 = new javax.swing.JButton();
        btn_Last1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        combo_filter = new javax.swing.JComboBox();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_TotalFee = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_TotalPaid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_TotalDue = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        lbltfee = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbltpaid = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbltdues = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblhfee = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lblhpaid = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lblhdues = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblmfee = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lblmpaid = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lblmdues = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        lblefee = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lblepaid = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        lbledues = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        lblufee = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        lblupaid = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lbludues = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        lblbfee = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lblbpaid = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        lblbdues = new javax.swing.JLabel();
        lblofee = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        lblopaid = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        lblodues = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_StudentPayreport = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_StudentProfile = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbltp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblpbch = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblpbd = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblpbc = new javax.swing.JLabel();
        btn_printrcp = new javax.swing.JButton();
        btn_PrintStudentDetails = new javax.swing.JButton();
        rbDatewise = new javax.swing.JRadioButton();
        rbAll = new javax.swing.JRadioButton();
        fdate = new com.toedter.calendar.JDateChooser();
        tdate = new com.toedter.calendar.JDateChooser();
        cmbSemester = new javax.swing.JComboBox();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Student's Report");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_2.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_First.setText("|<");
        btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FirstActionPerformed(evt);
            }
        });

        btn_Back.setText("<<");
        btn_Back.setMaximumSize(new java.awt.Dimension(45, 23));
        btn_Back.setMinimumSize(new java.awt.Dimension(45, 23));
        btn_Back.setPreferredSize(new java.awt.Dimension(45, 23));
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_Forward.setText(">>");
        btn_Forward.setMaximumSize(new java.awt.Dimension(45, 23));
        btn_Forward.setMinimumSize(new java.awt.Dimension(45, 23));
        btn_Forward.setPreferredSize(new java.awt.Dimension(45, 23));
        btn_Forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ForwardActionPerformed(evt);
            }
        });

        btn_Last.setText(">|");
        btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LastActionPerformed(evt);
            }
        });

        btn_First1.setText("|<");
        btn_First1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_First1ActionPerformed(evt);
            }
        });

        btn_Back1.setText("<<");
        btn_Back1.setMaximumSize(new java.awt.Dimension(45, 23));
        btn_Back1.setMinimumSize(new java.awt.Dimension(45, 23));
        btn_Back1.setPreferredSize(new java.awt.Dimension(45, 23));
        btn_Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Back1ActionPerformed(evt);
            }
        });

        btn_Forward1.setText(">>");
        btn_Forward1.setMaximumSize(new java.awt.Dimension(45, 23));
        btn_Forward1.setMinimumSize(new java.awt.Dimension(45, 23));
        btn_Forward1.setPreferredSize(new java.awt.Dimension(45, 23));
        btn_Forward1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Forward1ActionPerformed(evt);
            }
        });

        btn_Last1.setText(">|");
        btn_Last1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Last1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Forward, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(btn_First1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Back1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Forward1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Last1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_First1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Back1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_Forward1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_Last1))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_First, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_Forward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_Last))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Search");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel5.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 140, -1));

        combo_filter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Roll No", "Enrollment No", "Course", "First name", "Middle Name", "Last Name" }));
        combo_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_filterActionPerformed(evt);
            }
        });
        jPanel5.add(combo_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 12, 125, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Total Fee");

        lbl_TotalFee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TotalFee.setForeground(new java.awt.Color(51, 204, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total Paid");

        lbl_TotalPaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TotalPaid.setForeground(new java.awt.Color(51, 204, 0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Total Due");

        lbl_TotalDue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TotalDue.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_TotalFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_TotalPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_TotalDue, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TotalDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_TotalFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_TotalPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel29.setText("Tuition Payment:    RS");

        lbltfee.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setText("Paid");

        jLabel34.setText("Dues");

        jLabel30.setText("Hostel Payment:     RS");

        lblhfee.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setText("Paid");

        jLabel39.setText("Dues");

        jLabel41.setText("Mess Payment:       RS");

        jLabel43.setText("Paid");

        jLabel45.setText("Dues");

        jLabel47.setText("Exam Payment        RS");

        jLabel49.setText("Paid");

        jLabel51.setText("Dues");

        jLabel53.setText("Uniform Charge:     RS");

        jLabel55.setText("Paid");

        jLabel57.setText("Dues");

        jLabel59.setText("Bus Fare:                RS");

        jLabel61.setText("Paid");

        jLabel63.setText("Dues");

        jLabel60.setText("Other Charge:        RS");

        jLabel62.setText("Paid");

        jLabel64.setText("Dues");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(lbltfee, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(lblhfee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addComponent(lblmfee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel47))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblefee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblufee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbfee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblofee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel59)
                    .addComponent(jLabel60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblopaid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblodues, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbltpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblhpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltdues, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblhdues, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblbpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblupaid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblepaid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblmpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmdues, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbledues, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbludues, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblbdues, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltdues, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltfee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhdues, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblhfee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmfee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmdues, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblefee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblepaid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbledues, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblufee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblupaid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbludues, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbfee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbdues, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblofee, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblopaid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblodues, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_StudentPayreport.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jTable_StudentPayreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_StudentPayreport.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable_StudentPayreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_StudentPayreportMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_StudentPayreport);

        jTable_StudentProfile.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jTable_StudentProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_StudentProfile.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable_StudentProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable_StudentProfileMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_StudentProfileMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_StudentProfile);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Total Payment:           Rs  ");

        lbltp.setText("0.0");

        jLabel4.setText("Payment By Cheque: Rs");

        lblpbch.setText("0.0");

        jLabel6.setText("Payment By DD:         Rs");

        lblpbd.setText("0.0");

        jLabel8.setText("Payment By Cash:      Rs");

        lblpbc.setText("0.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblpbch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblpbd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblpbc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltp, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpbch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblpbd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpbc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        btn_printrcp.setText("Print Reciept");
        btn_printrcp.setToolTipText("Click to print duplicate reciept");
        btn_printrcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printrcpActionPerformed(evt);
            }
        });

        btn_PrintStudentDetails.setText("Print Details");
        btn_PrintStudentDetails.setToolTipText("Click to find students report");
        btn_PrintStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintStudentDetailsActionPerformed(evt);
            }
        });

        rbDatewise.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbDatewise);
        rbDatewise.setText("Date Wise");
        rbDatewise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDatewiseActionPerformed(evt);
            }
        });

        rbAll.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbAll);
        rbAll.setText("All");
        rbAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAllActionPerformed(evt);
            }
        });

        fdate.setDateFormatString("dd-MM-yy");
        fdate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fdatePropertyChange(evt);
            }
        });

        tdate.setDateFormatString("dd-MM-yy");
        tdate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tdatePropertyChange(evt);
            }
        });

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st", "2nd", "3rd", "4th" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(349, 349, 349)
                                .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_printrcp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbDatewise)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_PrintStudentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_printrcp)
                                .addComponent(rbDatewise)
                                .addComponent(rbAll))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(fdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_PrintStudentDetails))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void retrieveFilteredDetails() {
        String item = txt_search.getText();
        int selection = combo_filter.getSelectedIndex();
        String coloumn_name = "";
        try {
            con = Util.getConnection();
            switch (selection) {
                case 0:
                    coloumn_name = "roll_number";
                    break;
                case 1:
                    coloumn_name = "enrollment_number";
                    break;
                case 2:
                    coloumn_name = "course";
                    break;
                case 3:
                    coloumn_name = "first_name";
                    break;
                case 4:
                    coloumn_name = "middle_name";
                    break;
                case 5:
                    coloumn_name = "last_name";
                    break;

            }
            psmnt = con.prepareStatement("select roll_number as 'ROLL NUMBER', enrollment_number as 'ENROLLMENT NUMBER', concat(first_name,' ', middle_name,' ', last_name) as 'NAME', gender as 'GENDER', dob as 'DATE OF BIRTH', father_name as 'FATHER NAME', mother_name as 'MOTHER NAME', bloodgroup as 'BLOOD GROUP', marital_status as 'MARITAL STATUS', religion as 'RELIGION', cast as 'CASTE', nationality as 'NATIONALITY', course as 'COURSE', branch as 'BRANCH', semester as 'SEMESTER', session as 'SESSION' from student_details where " + coloumn_name + " like '" + item + "%' limit " + from + ", 20 ");
            rs = psmnt.executeQuery();

            jTable_StudentProfile.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            Coloumnautosizer.sizeColumnsToFit(jTable_StudentProfile);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "some filter search problem " + e.getMessage());
            e.printStackTrace();

        }
    }

    public void retrievefeedetails() {
        double hf = 0, tf = 0, mf = 0, ef = 0, uf = 0, bf = 0, of = 0;
        double hp = 0, tp = 0, mp = 0, ep = 0, up = 0, bp = 0, op = 0;
        double dh, dt, dm, de, du, db, dof;
        int row = jTable_StudentProfile.getSelectedRow();
        try {
            con = Util.getConnection();
            psmnt = con.prepareStatement("select thf, ttf, tmf, tef, tuf, tbf,tof from fee_details where roll_number = '" + jTable_StudentProfile.getValueAt(row, 0).toString() + "' and semester = '" + cmbSemester.getSelectedItem().toString() + "' ");
            rs = psmnt.executeQuery();
            if (rs.next()) {

                hf = rs.getString(1) == null ? 0.0 : Double.parseDouble(rs.getString(1));
                lblhfee.setText(rs.getString(1));
                tf = rs.getString(2) == null ? 0.0 : Double.parseDouble(rs.getString(2));
                lbltfee.setText(rs.getString(2));
                mf = rs.getString(3) == null ? 0.0 : Double.parseDouble(rs.getString(3));
                lblmfee.setText(rs.getString(3));
                ef = rs.getString(4) == null ? 0.0 : Double.parseDouble(rs.getString(4));
                lblefee.setText(rs.getString(4));
                uf = rs.getString(5) == null ? 0.0 : Double.parseDouble(rs.getString(5));
                lblufee.setText(rs.getString(5));
                bf = rs.getString(6) == null ? 0.0 : Double.parseDouble(rs.getString(6));
                lblbfee.setText(rs.getString(6));
                of = rs.getString(7) == null ? 0.0 : Double.parseDouble(rs.getString(7));
                lblofee.setText(rs.getString(7));

            }

            psmnt = con.prepareStatement("select sum(hostelfee), sum(tutionfee), sum(messfee), sum(examfee), sum(uniformcharge), sum(busfare),sum(other) from pay_report where rollno = '" + jTable_StudentProfile.getValueAt(row, 0).toString() + "' and semester = '" + cmbSemester.getSelectedItem().toString() + "' ");
            rs = psmnt.executeQuery();
            if (rs.next()) {
                hp = rs.getString(1) == null ? 0.0 : Double.parseDouble(rs.getString(1));
                lblhpaid.setText(String.valueOf(hp));
                tp = rs.getString(2) == null ? 0.0 : Double.parseDouble(rs.getString(2));
                lbltpaid.setText(String.valueOf(tp));
                mp = rs.getString(3) == null ? 0.0 : Double.parseDouble(rs.getString(3));
                lblmpaid.setText(String.valueOf(mp));
                ep = rs.getString(4) == null ? 0.0 : Double.parseDouble(rs.getString(4));
                lblepaid.setText(String.valueOf(ep));
                up = rs.getString(5) == null ? 0.0 : Double.parseDouble(rs.getString(5));
                lblupaid.setText(String.valueOf(up));
                bp = rs.getString(6) == null ? 0.0 : Double.parseDouble(rs.getString(6));
                lblbpaid.setText(String.valueOf(bp));
                op = rs.getString(7) == null ? 0.0 : Double.parseDouble(rs.getString(7));
                lblopaid.setText(String.valueOf(op));
            }

            dh = hf - hp;
            dt = tf - tp;
            dm = mf - mp;
            de = ef - ep;
            du = uf - up;
            db = bf - bp;
            dof = of - op;

            lbltdues.setText(String.valueOf(dt));
            lblhdues.setText(String.valueOf(dh));
            lblmdues.setText(String.valueOf(dm));
            lbledues.setText(String.valueOf(de));
            lbludues.setText(String.valueOf(du));
            lblbdues.setText(String.valueOf(db));
            lblodues.setText(String.valueOf(dof));


            //Total Fee details
            double totalfee = hf + tf + mf + ef + uf + bf + of;
            double totalpaid = hp + tp + mp + ep + up + bp + op;
            double totaldues = totalfee - totalpaid;

            lbl_TotalFee.setText(String.valueOf(totalfee));
            lbl_TotalPaid.setText(String.valueOf(totalpaid));
            lbl_TotalDue.setText(String.valueOf(totaldues));

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void retrieveStudentdetails() {
        try {
            con = Util.getConnection();
            psmnt = con.prepareStatement("select roll_number as 'ROLL NUMBER', enrollment_number as 'ENROLLMENT NUMBER', first_name as 'FIRST NAME', middle_name 'MIDDLE NAME', last_name  as 'LAST NAME', gender as 'GENDER', dob as 'DATE OF BIRTH', father_name as 'FATHER NAME', mother_name as 'MOTHER NAME', bloodgroup as 'BLOOD GROUP', marital_status as 'MARITAL STATUS', religion as 'RELIGION', cast as 'CASTE', nationality as 'NATIONALITY', course as 'COURSE', branch as 'BRANCH', semester as 'SEMESTER', session as 'SESSION' from student_details limit " + from + ", 20");
            rs = psmnt.executeQuery();

            jTable_StudentProfile.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            Coloumnautosizer.sizeColumnsToFit(jTable_StudentProfile);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "some filter search problem " + e.getMessage());
            e.printStackTrace();

        }
    }

    private void btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FirstActionPerformed
        // TODO add your handling code here:
        if (!txt_search.getText().isEmpty()) {
            retrieveFilteredDetails();
        } else {
            from = 0;
            retrieveStudentdetails();
        }
    }//GEN-LAST:event_btn_FirstActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        if (!txt_search.getText().isEmpty()) {
            retrieveFilteredDetails();
        } else {
            if (from <= 0) {
                from = 0;

                retrieveStudentdetails();
            } else {
                from -= 20;

                retrieveStudentdetails();
            }
        }
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_ForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ForwardActionPerformed
        // TODO add your handling code here:
        if (!txt_search.getText().isEmpty()) {
            retrieveFilteredDetails();
        } else {
            if (from + 2 > rowcount) {

                retrieveStudentdetails();
                from -= 2;

            } else if (from < 0) {

                from = 0;
                retrieveStudentdetails();

            } else {

                from += 2;

                retrieveStudentdetails();
            }
        }
    }//GEN-LAST:event_btn_ForwardActionPerformed

    private void btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LastActionPerformed
        // TODO add your handling code here:
        try {
            con = Util.getConnection();
            stmt = con.createStatement();
            rs = stmt.executeQuery("select count(roll_number) from student_details ");
            while (rs.next()) {
                rowcount = rs.getInt(1);
            }

            if (!txt_search.getText().isEmpty()) {
                retrieveFilteredDetails();
            } else {
                if (rowcount != 0) {
                    int rem = rowcount % 20;
                    if (rem != 0) {

                        from = rowcount / 20 * 20;
                        retrieveStudentdetails();

                    } else {

                        from = rowcount - 20;
                        retrieveStudentdetails();
                    }

                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error coloumn" + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_LastActionPerformed

    public void retrieveReciept() {

        String datefrom = "";
        String dateto = "";
        try {
            // TODO add your handling code here:
            con = Util.getConnection();
            if (rbAll.isSelected()) {
                System.out.println("rfrom " + rfrom);
                psmnt = con.prepareStatement("select rcpno as 'RECIEPT NUMBER', rdate as 'DATE OF PAYMENT', tutionfee as 'TUTION FEE', hostelfee as 'HOSTEL FEE', messfee as 'MESS FEE', examfee as 'EXAM FEE', uniformcharge as 'UNIFORM CHARGE', busfare as 'BUS FARE', other as 'EXTRA FEE', amount as 'AMOUNT' from PAY_REPORT where rollno = '" + selection + "' limit " + rfrom + ", 20 ");

                rs = psmnt.executeQuery();

                jTable_StudentPayreport.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                Coloumnautosizer.sizeColumnsToFit(jTable_StudentPayreport);
            } else if (rbDatewise.isSelected()) {
                System.out.println("rfrom " + rfrom);


                try {
                    con = Util.getConnection();
                    stmt = con.createStatement();
                    rs = stmt.executeQuery("select * from dateformat");
                    if (rs.next()) {
                        Date d = fdate.getDate();
                        Date d1 = tdate.getDate();
                        SimpleDateFormat formatter = new SimpleDateFormat(rs.getString(1));
                        String s = formatter.format(d);
                        String t = formatter.format(d1);
                        datefrom = s;
                        dateto = t;
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error :- " + ex.toString());
                    ex.printStackTrace();
                }


                System.out.println("from " + datefrom + " to " + dateto);
                psmnt = con.prepareStatement("select rcpno as 'RECIEPT NUMBER', rdate as 'DATE OF PAYMENT', tutionfee as 'TUTION FEE', hostelfee as 'HOSTEL FEE', messfee as 'MESS FEE', examfee as 'EXAM FEE', uniformcharge as 'UNIFORM CHARGE', busfare as 'BUS FARE', other as 'EXTRA FEE', amount as 'AMOUNT' from PAY_REPORT where rollno = '" + selection + "' and rdate between '" + datefrom + "' and '" + dateto + "' limit " + rfrom + ", 20 ");

                rs = psmnt.executeQuery();

                jTable_StudentPayreport.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                Coloumnautosizer.sizeColumnsToFit(jTable_StudentPayreport);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please select a table.");
            ex.printStackTrace();
        } finally {
            Util.closeResultset(rs);
            Util.closeStatement(psmnt);
            Util.closeConnection(con);
        }
    }

    private void btn_First1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_First1ActionPerformed
        // TODO add your handling code here:
        rfrom = 0;

        retrieveReciept();
    }//GEN-LAST:event_btn_First1ActionPerformed

    private void btn_Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Back1ActionPerformed
        // TODO add your handling code here:

        if (rfrom <= 0) {
            rfrom = 0;

            retrieveReciept();
        } else {
            rfrom -= 20;

            retrieveReciept();
        }
    }//GEN-LAST:event_btn_Back1ActionPerformed

    private void btn_Forward1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Forward1ActionPerformed
        // TODO add your handling code here:

        if (rfrom + 20 > rowcount) {

            retrieveReciept();
            rfrom -= 20;

        } else if (from < 0) {

            rfrom = 0;
            retrieveReciept();

        } else {

            rfrom += 20;

            retrieveReciept();
        }
    }//GEN-LAST:event_btn_Forward1ActionPerformed

    private void btn_Last1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Last1ActionPerformed
        // TODO add your handling code here:

        try {
            con = Util.getConnection();
            stmt = con.createStatement();
            rs = stmt.executeQuery("select count(rcpno) from pay_report ");
            while (rs.next()) {
                rowcount = rs.getInt(1);
            }
            if (rowcount != 0) {
                int rem = rowcount % 20;
                if (rem != 0) {

                    rfrom = rowcount / 20 * 20;
                    retrieveReciept();

                } else {

                    rfrom = rowcount - 20;
                    retrieveReciept();
                }
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btn_Last1ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        retrieveFilteredDetails();
    }//GEN-LAST:event_txt_searchKeyReleased

    private void combo_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_filterActionPerformed
    }//GEN-LAST:event_combo_filterActionPerformed

    public void retrievecash() {
        int row = jTable_StudentPayreport.getSelectedRow();
        try {
            con = Util.getConnection();
            psmnt = con.prepareStatement("select amount from pay_report where rcpno = '" + jTable_StudentPayreport.getValueAt(row, 0).toString() + "' ");
            rs = psmnt.executeQuery();
            if (rs.next()) {
                lbltp.setText(rs.getString(1));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void retrievechaque() {
        int row = jTable_StudentPayreport.getSelectedRow();
        try {
            con = Util.getConnection();
            psmnt = con.prepareStatement("select sum(amount) from cheque where rcpno = '" + jTable_StudentPayreport.getValueAt(row, 0).toString() + "' ");
            rs = psmnt.executeQuery();
            if (rs.next()) {
                lblpbch.setText(rs.getString(1));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void retrievedd() {
        int row = jTable_StudentPayreport.getSelectedRow();
        try {
            con = Util.getConnection();
            psmnt = con.prepareStatement("select sum(amount) from dd where rcpno = '" + jTable_StudentPayreport.getValueAt(row, 0).toString() + "' ");
            rs = psmnt.executeQuery();
            if (rs.next()) {
                lblpbd.setText(rs.getString(1));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void jTable_StudentPayreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StudentPayreportMouseClicked
        // TODO add your handling code here:

        retrievecash();
        retrievechaque();
        retrievedd();

        double a = (lbltp.getText() == null) ? 0.0 : Double.parseDouble(lbltp.getText());
        double b = (lblpbch.getText() == null) ? 0.0 : Double.parseDouble(lblpbch.getText());
        double c = (lblpbd.getText() == null) ? 0.0 : Double.parseDouble(lblpbd.getText());
        double d = a - (b + c);
        lblpbc.setText(String.valueOf(d));
    }//GEN-LAST:event_jTable_StudentPayreportMouseClicked

    private void jTable_StudentProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StudentProfileMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_StudentProfileMouseEntered

    private void jTable_StudentProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StudentProfileMousePressed
        // TODO add your handling code here:
        row = jTable_StudentProfile.getSelectedRow();
        selection = jTable_StudentProfile.getValueAt(row, 0).toString();
        retrieveReciept();
        retrievefeedetails();
    }//GEN-LAST:event_jTable_StudentProfileMousePressed

    public void printReciept() {

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(this);
        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }


    }

    private void btn_printrcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printrcpActionPerformed
        // TODO add your handling code here:
        int row = jTable_StudentPayreport.getSelectedRow();
        System.out.println("Row ;-" + row);
        if (row != -1) {
            printReciept();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row!!");
        }
    }//GEN-LAST:event_btn_printrcpActionPerformed

    private void btn_PrintStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintStudentDetailsActionPerformed
        // TODO add your handling code here:
        int row = jTable_StudentProfile.getSelectedRow();
        if (row != -1) {
            String RollNumber = "Roll Number :- " + jTable_StudentProfile.getValueAt(row, 0).toString();
            String fName = "Name :- " + jTable_StudentProfile.getValueAt(row, 2).toString();
            String Msg = RollNumber + "  " + fName;

            try {
                PrinterJob job = PrinterJob.getPrinterJob();
                job.setPrintable(this);

                MessageFormat header = new MessageFormat("Reciept Report (" + Msg + ")");
                MessageFormat footer = new MessageFormat("Páge{0,number,integer}");
                try {
                    jTable_StudentPayreport.print(JTable.PrintMode.FIT_WIDTH, header, footer);
                } catch (java.awt.print.PrinterException e) {

                    System.err.format("cant Print %s%n", e.getMessage());
                    e.printStackTrace();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row.");
        }
    }//GEN-LAST:event_btn_PrintStudentDetailsActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        fdate.setDate(new Date());
        tdate.setDate(new Date());
        rbAll.setSelected(true);

    }//GEN-LAST:event_formInternalFrameOpened

    private void rbAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAllActionPerformed
        // TODO add your handling code here:
        retrieveReciept();
    }//GEN-LAST:event_rbAllActionPerformed

    private void rbDatewiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDatewiseActionPerformed
        // TODO add your handling code here:
        retrieveReciept();
    }//GEN-LAST:event_rbDatewiseActionPerformed

    private void fdatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fdatePropertyChange
        // TODO add your handling code here:
        retrieveReciept();
    }//GEN-LAST:event_fdatePropertyChange

    private void tdatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tdatePropertyChange
        // TODO add your handling code here:
        retrieveReciept();
    }//GEN-LAST:event_tdatePropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Back1;
    private javax.swing.JButton btn_First;
    private javax.swing.JButton btn_First1;
    private javax.swing.JButton btn_Forward;
    private javax.swing.JButton btn_Forward1;
    private javax.swing.JButton btn_Last;
    private javax.swing.JButton btn_Last1;
    private javax.swing.JButton btn_PrintStudentDetails;
    private javax.swing.JButton btn_printrcp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbSemester;
    private javax.swing.JComboBox combo_filter;
    private com.toedter.calendar.JDateChooser fdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_StudentPayreport;
    private javax.swing.JTable jTable_StudentProfile;
    private javax.swing.JLabel lbl_TotalDue;
    private javax.swing.JLabel lbl_TotalFee;
    private javax.swing.JLabel lbl_TotalPaid;
    private javax.swing.JLabel lblbdues;
    private javax.swing.JLabel lblbfee;
    private javax.swing.JLabel lblbpaid;
    private javax.swing.JLabel lbledues;
    private javax.swing.JLabel lblefee;
    private javax.swing.JLabel lblepaid;
    private javax.swing.JLabel lblhdues;
    private javax.swing.JLabel lblhfee;
    private javax.swing.JLabel lblhpaid;
    private javax.swing.JLabel lblmdues;
    private javax.swing.JLabel lblmfee;
    private javax.swing.JLabel lblmpaid;
    private javax.swing.JLabel lblodues;
    private javax.swing.JLabel lblofee;
    private javax.swing.JLabel lblopaid;
    private javax.swing.JLabel lblpbc;
    private javax.swing.JLabel lblpbch;
    private javax.swing.JLabel lblpbd;
    private javax.swing.JLabel lbltdues;
    private javax.swing.JLabel lbltfee;
    private javax.swing.JLabel lbltp;
    private javax.swing.JLabel lbltpaid;
    private javax.swing.JLabel lbludues;
    private javax.swing.JLabel lblufee;
    private javax.swing.JLabel lblupaid;
    private javax.swing.JRadioButton rbAll;
    private javax.swing.JRadioButton rbDatewise;
    private com.toedter.calendar.JDateChooser tdate;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics g, PageFormat pf, int page) throws PrinterException {
        if (page > 0) { /*
             * We have only one page, and 'page' is zero-based
             */
            return NO_SUCH_PAGE;
        }

        /*
         * User (0,0) is typically outside the imageable area, so we must
         * translate by the X and Y values in the PageFormat to avoid clipping
         */

        int row = jTable_StudentPayreport.getSelectedRow();
        try {
            con = Util.getConnection();
            psmnt = con.prepareStatement("select rcpno, firstname, middlename, lastname, course, session, semester, address, amount, rdate from pay_report where rcpno = '" + jTable_StudentPayreport.getValueAt(row, 0).toString() + "'");
            rs = psmnt.executeQuery();
            if (rs.next()) {
                String rcpno = rs.getString(1);
                String fname;
                String mname;
                String lname;
                String name;
                String course = rs.getString(5);
                String session = rs.getString(6);
                String sem = rs.getString(7);
                String address = rs.getString(8);
                String total = rs.getString(9);
                String date = rs.getString(10);

                if (rs.getString(2) != null) {
                    fname = rs.getString(2);
                } else {
                    fname = "";
                }
                if (rs.getString(3) != null) {
                    mname = rs.getString(3);
                } else {
                    mname = "";
                }
                if (rs.getString(4) != null) {
                    lname = rs.getString(4);
                } else {
                    lname = "";
                }
                name = fname + " " + mname + " " + lname;
                Graphics2D g2d = (Graphics2D) g;
                g2d.translate(pf.getImageableX(), pf.getImageableY());

                /*
                 * Now we perform our rendering
                 */
                Font font = new Font("Tahoma", Font.BOLD, 17);
                g2d.setFont(font);

                g.drawString("MONEY RECIEPT", 225, 151);

                Image logoImage = null, rupeeImage = null, selectImage = null;
                try {
                    logoImage = ImageIO.read(getClass().getResource("/Image/nilai.png"));
                    rupeeImage = ImageIO.read(getClass().getResource("/Image/ruppee.png"));
                    selectImage = ImageIO.read(getClass().getResource("/Image/select.png"));
                } catch (IOException ex) {
                }
                // setIconImage(logoImage);
                g.drawImage(logoImage, 30, 20, null);

                //   setIconImage(rupeeImage);
                g.drawImage(rupeeImage, 440, 320, null);

                // lbl_rupee.paint(g.create(440, 320, width, height));

                Font font1 = new Font("Tahoma", Font.PLAIN, 10);
                g2d.setFont(font1);

                g.drawString("Date _________________", 50, 180);
                g.drawString(date, 80, 180);
                g.drawString("No.", 500, 180);

                g.drawString("Recieved From _________________________________________________________________________________", 50, 210);
                g.drawString(name, 120, 210);
                g.drawString("Rs. in Words ___________________________________________________________________________________", 50, 240);


                double nettotal = Double.parseDouble(total);
                NumToWords w = new NumToWords();
                String word = w.convert((int) Math.round(nettotal));

                int l = word.length();
                String s1 = null;
                String s2 = null;
                String totalword;
                if (l != 0) {
                    s1 = word.substring(0, 1).toUpperCase();
                    s2 = word.substring(1, l);
                    totalword = s1 + s2 + " Only";
                } else {
                    totalword = "Zero Only";
                }
                System.out.println("word =" + totalword);

                g.drawString(totalword, 120, 240);
                g.drawString("Address _______________________________________________________________________________________", 50, 270);
                g.drawString(address, 90, 270);
                g.drawString("Course Programme ____________________________Session______________________Semester______________", 50, 300);
                g.drawString(course, 140, 300);
                g.drawString(total, 480, 340);
                g.drawString(session, 340, 300);
                g.drawString(sem, 500, 300);
                g.drawRect(60, 320, 80, 20);
                g.drawRect(60, 350, 80, 20);
                g.drawRect(60, 380, 80, 20);
                g.drawString("Account", 65, 335);
                g.drawString("Payment", 65, 365);
                g.drawString("Balance Due", 65, 395);
                g.drawRect(145, 320, 80, 20);
                g.drawRect(145, 350, 80, 20);
                g.drawRect(145, 380, 80, 20);
                g.drawRect(230, 320, 30, 20);
                g.drawRect(230, 350, 30, 20);
                g.drawRect(230, 380, 30, 20);

                g.drawOval(265, 320, 20, 20);
                g.drawOval(265, 350, 20, 20);
                g.drawOval(265, 380, 20, 20);
                g.drawString("Cash", 290, 335);
                g.drawString("Cheque", 290, 365);
                g.drawString("Demand Draft", 290, 395);
                if (!lblpbc.getText().trim().equals("0.0")) {
                    g.drawImage(selectImage, 265, 320, null);
                }
                if (lblpbch.getText() != null) {
                    g.drawImage(selectImage, 265, 350, null);
                }
                if (lblpbd.getText() != null) {
                    g.drawImage(selectImage, 265, 380, null);
                }




//        if (rb_macc.isSelected()) {
//            g.drawString("Multiple Acc".toString(), 150, 335);
//        } else {
//            g.drawString(txt_acc.getSelectedItem().toString(), 150, 335);
//        }
                g.drawString(total, 150, 365);
                //g.drawString("", 150, 395);

                Font font2 = new Font("Tahoma", Font.BOLD, 8);
                g2d.setFont(font2);

                g.drawString("Thakurgaon, Ranchi, Jharkhand. Phone : 06531-277785. E-mail : info@nilai.in . Website :www.nilai.in", 80, 440);
                Font font20 = new Font("Tahoma", Font.BOLD, 10);
                g2d.setFont(font20);

                g.drawString("Authorised Signatory", 460, 400);

                Font font3 = new Font("Tahoma", Font.PLAIN, 7);
                g2d.setFont(font3);



                Font f = new Font("Tahoma", Font.BOLD, 9);
                g2d.setFont(f);


                g.drawString(rcpno, 520, 180);
                /*
                 * PLAIN lines
                 */
                Graphics2D g1 = (Graphics2D) g;
                g1.translate(pf.getImageableX(), pf.getImageableY());
                Font f5 = new Font("Tahoma", Font.PLAIN, 1);
                g1.setFont(f5);

                g2d = (Graphics2D) g;
                g2d.setStroke(new BasicStroke(2));

                /*
                 * lines for tax invoice and one line below part
                 */
                g.drawRect(440, 320, 120, 30);
                g.drawLine(465, 320, 465, 350);
                g.drawLine(0, 130, 600, 130);
                g.drawLine(0, 430, 600, 430);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return PAGE_EXISTS;
    }
}
